---
title: "R Practice: Tidy Data and Joins"
format: html
---
```{r}
library(readr)
library(dplyr)
library(lubridate)
```

## Read in the data
```{r}
bird_observations <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=53edaa7a0e083013d9bf20322db1780e")
surveys <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=b2466fa5cb5ed7ee1ea91398fc291c59")
sites <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=81bf72420e69077097fb0790dcdc63a6")
taxalist <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-cap.256.10&entityid=58f863b7e3066e68536a9cacdc7bd58e")
```
```{r}
# returns dimensions of the dataframe by number of rows and number of cols
dim(bird_observations)

# returns the top six rows of the dataframe
head(bird_observations)

# returns all the columns and some info about the cols
glimpse(bird_observations)

# similar to glimpse but returns some summary statistics about the cols
summary(bird_observations)

# returns column names 
names(bird_observations)

# returns unique values in a column. In this case we can see all the different bird species IDs
unique(bird_observations$species_id)
```
```{r}
head(taxalist)
```
```{r}
# Subset of bird observations that only contains observations for birds with species id BHCO and RWBL, and from sites with site ID LI-W and NU-C.
birds_subset <- bird_observations %>%
  filter(species_id %in% c("BHCO", "RWBL")) %>%
  filter(site_id %in% c("LI-W", "NU-C"))

head(birds_subset)
```
```{r}
# syntax using pipe
birds_left <- birds_subset %>% 
  left_join(y = sites, by = "site_id")

head(birds_left)
```
```{r}
birds_full <- birds_subset %>%
  full_join(y = sites, by = "site_id")
  
head(birds_full)
```
# inner join to merge birds_subset with taxalist data
```{r}
birds_inner <- birds_subset %>% 
  inner_join(y = taxalist, by = "species_id")

head(birds_inner)
```
```{r}
birds_left_taxalist <- birds_subset %>% 
  left_join(y = taxalist, by = "species_id")

head(birds_left_taxalist)
```
```{r}
bird_observations <- bird_observations %>% 
  rename(bird_obs_notes = notes)
```
```{r}
bird_obs_subset <- bird_observations %>% 
  full_join(y = taxalist, by = "species_id") %>% 
  full_join(y = sites, by = "site_id") %>% 
  full_join(y = surveys, by = c("site_id", "survey_id")) %>%  
  select(survey_date, common_name, park_name, bird_count, observer)

head(bird_obs_subset)
```
```{r}
unique(bird_obs_subset$observer)
```
```{r}
bird_obs_subset <- bird_obs_subset %>% 
  mutate(observer = if_else(condition = observer == "Josh Burns", 
                            true = "J. Burns", 
                            false = observer))

unique(bird_obs_subset$observer)
```
```{r}
bird_obs_subset <- bird_obs_subset %>% 
  mutate(survey_month = lubridate::month(survey_date)) %>% 
  mutate(survey_month = as.factor(survey_month)) %>% 
  dplyr::relocate(survey_month, .after = survey_date) %>% 
  filter(park_name %in% c("Lindo", "Orme", "Palomino", "Sonrisa")) %>% 
  group_by(park_name, survey_month) %>% 
  summarize(tot_bird_count_month = n())

head(bird_obs_subset)
```

